# Generated by Django 3.1.13 on 2021-08-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megan_wedding', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayguest',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='nightguest',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='dayguest',
            name='message',
        ),
        migrations.RemoveField(
            model_name='nightguest',
            name='message',
        ),
        migrations.AddField(
            model_name='dayguest',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nightguest',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
