# Generated by Django 3.1.13 on 2021-09-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megan_wedding', '0002_auto_20210826_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayguest',
            name='message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dayguest',
            name='number_adult',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dayguest',
            name='number_children',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nightguest',
            name='message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nightguest',
            name='number_adult',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nightguest',
            name='number_children',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
